/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sat_server_ServerImpl */

#ifndef _Included_sat_server_ServerImpl
#define _Included_sat_server_ServerImpl
#ifdef __cplusplus
extern "C" {
#endif
#undef sat_server_ServerImpl_serialVersionUID
#define sat_server_ServerImpl_serialVersionUID -3215090123894869218LL
/* Inaccessible static: logname */
/* Inaccessible static: log */
#undef sat_server_ServerImpl_serialVersionUID
#define sat_server_ServerImpl_serialVersionUID -4100238210092549637LL
#undef sat_server_ServerImpl_serialVersionUID
#define sat_server_ServerImpl_serialVersionUID 4974527148936298033LL
/* Inaccessible static: portParamTypes */
/* Inaccessible static: portFactoryParamTypes */
/* Inaccessible static: class_00024java_00024rmi_00024server_00024RMIClientSocketFactory */
/* Inaccessible static: class_00024java_00024rmi_00024server_00024RMIServerSocketFactory */
/* Inaccessible static: class_00024java_00024rmi_00024server_00024ServerRef */
/* Inaccessible static: hostname */
/*
 * Class:     sat_server_ServerImpl
 * Method:    process
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_sat_server_ServerImpl_process
  (JNIEnv *, jobject, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
